name: LCCPlugin
version: ${project.version}
main: lcc.lusocraftchampionship.LCCPlugin
authors: [ Smili, MiniGahmer ]
description: LCC Plugin
depend: [ ProtocolLib ]
api-version: '1.20'

commands:
  reloadlcc:
  startmgtest:
  startflagsofwar:
  startgravitywars: