name: LCC
version: ${project.version}
main: lcc.lusocraftchampionship.Lusocraftchampionship
authors: [ Smili, MiniGahmer ]
description: LCC Plugin
depend: [ ProtocolLib ]
api-version: '1.20'

commands:
  startgravitywars:
  startwildwestbounty:
  startlcc:
  stoplcc:
  reloadlcc:
  togglegravity: