name: LCCPlugin
version: 1.0-SNAPSHOT
main: lcc.lusocraftchampionship.Lusocraftchampionship.LCCPlugin
authors: [ Smili, MiniGahmer ]
description: LCC Plugin
depend: [ ProtocolLib ]
api-version: '1.20'

commands:
  startgravitywars:
  startwildwestbounty:
  startlcc:
  stoplcc:
  reloadlcc:
  togglegravity: